### ISSUE TITLE
Any way to save / restore the database from disk?

### ISSUE THREAD

**Issue by winkmichael** [SirJosh3917/StringDB#8]
Hello, I've read over the main page and the example and I don't see a "file" option. Is there any way to save / restore the database from disk?

Thanks

**Comment by monoclex** [comment]
The example on the front page opens a database file on disk named `database.db` - is this what you were looking for? If memory serves me correctly, you *should* be able to pass in a `FileStream` too, but it's been a while.

```cs
using var db = new DatabaseBuilder()
	.UseIODatabase(StringDBVersion.Latest, "database.db", out var optimalTokenSource)
	.WithBuffer(1000)
	.WithTranform(StringTransformation.Default, StringTransformation.Default);
	
foreach (var (key, value) in db.EnumerateOptimally(optimalTokenSource))
{
	// do something with the key and value
}
```

**Comment by winkmichael** [comment]
yes, thank you, I suppose I could easily take the stream and write it to file. thanks

**Comment by monoclex** [comment]
> I could easily take the stream and write it to file

I would be careful about messing with the `FileStream` object itself - you should let StringDB handle disposing the `FileStream` (which should, in effect, save it), ideally within a using statement/block or manually calling `.Dispose()` in some `finally` block.

The reason I recommend against messing with it yourself, is that StringDB employs a caching layer between it and `FileStream`. This caching layer exists because the implementation of `FileStream` in older versions of .NET do not use any caching, although [newer versions do](https://devblogs.microsoft.com/dotnet/file-io-improvements-in-dotnet-6/). I have personally ran into extremely hard to debug bugs where, if the `FileStream` was de-synchronised with what the caching mechanism, major data corruption would occur.
